name: Build

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  _pre:
    name: Variables
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Variables
        run: |
          gh variable set -f ${{ inputs.config-path }}
          gh variable list
          env

  # build:
  # test:
  # scan:
  # save_scan: