name: build-app

on:
  workflow_run:
    workflows: [Build App]
    types: [requested]

jobs:
  _pre:
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        run: |
          gh variable set -f dev.env
          env

  # build:
  # test:
  # scan:
  # save_scan: