name: Main

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        descrption: Release Version
        type: string
      target-env:
        required: false
        description: Release Environment
        type: choice
        default: 'github'
        options:
        - github
        - dev
        - stage
        - prod
      skip-tests:
        required: false
        description: Skip Tests
        type: boolean
        default: 'false'
      skip-infra:
        required: false
        description: Skip Infrastructure
        type: boolean
        default: 'false'
      skip-scan:
        required: false
        description: Skip Scanning
        type: boolean
        default: 'false'
      new-cache:
        required: false
        description: Re-build cache
        type: boolean
        default: 'false'

jobs:
  # app_cache:
  # cloud_cache:
#   _pre:
#     name: Variables
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo VERSION ${{ github.event.inputs.version }}
#           echo TARGET_ENV ${{ github.event.inputs.target-env }}
#           echo SKIP_TESTS ${{ github.event.inputs.skip-tests }}
#           echo SKIP_INFRA ${{ github.event.inputs.skip-infra }}
#           echo SKIP_SCAN ${{ github.event.inputs.skip-scan }}
#           echo NEW_CACHE ${{ github.event.inputs.new-cache }}
#           echo BRANCH ${{ github.ref_name }}

  build_app:
    name: Build App
    runs-on: ubuntu-latest
    # needs: [_pre]
    env:
      GH_TOKEN: ${{ github.token }}
      GH_WORKFLOW_BUILD: build.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        if: github.event.inputs.target-env == 'github' || github.event.inputs.target-env == 'dev'
        # needs: [ app_cache ]
        run: |
          gh workflow list --all
          gh workflow run ${{ env.GH_WORKFLOW_BUILD }} --ref ${{ github.ref_name }}

  # deploy_dev:
  # draft_release:
