name: Main

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        descrption: Release Version
        type: string
      target-env:
        required: false
        description: Release Environment
        type: choice
        default: 'github'
        options:
        - github
        - dev
        - stage
        - prod
      skip-tests:
        required: false
        description: Skip Tests
        type: boolean
        default: 'false'
      skip-infra:
        required: false
        description: Skip Infrastructure
        type: boolean
        default: 'false'
      skip-scan:
        required: false
        description: Skip Scanning
        type: boolean
        default: 'false'
      new-cache:
        required: false
        description: Re-build cache
        type: boolean
        default: 'false'

jobs:
  # app_cache
  build_app:
    name: Build App
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: ./.github/workflows/build.yaml

    # runs-on: ubuntu-latest
    # env:
    #   GH_TOKEN: ${{ github.token }}
    #   GH_WORKFLOW_BUILD: build.yaml
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: Build
    #     if: github.event.inputs.target-env == 'github' || github.event.inputs.target-env == 'dev'
    #     # needs: [ app_cache ]
    #     run: |
    #       gh workflow run ${{ env.GH_WORKFLOW_BUILD }} --ref ${{ github.ref_name }}

  # deploy_dev:
  # draft_release:
